name: Node.js CI

on:
  push:
    branches:
      - master  # Set the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change to your desired Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
